### ISSUE TITLE
Panic due to unwrap()

### ISSUE THREAD

**Issue by andrew-kolesnikov** [apollographql/federation-rs#415]
Receiving the following panic that I traced down to this line: https://github.com/apollographql/federation-rs/blob/6f72355b98d5389eba53625d0990d7cb0eb80ec9/federation-2/router-bridge/src/worker.rs#L98C19-L98C31 

```
panicked at 'called `Result::unwrap()` on an `Err` value: TypeError: Error parsing args at position 1: missing field `id`
    at send (worker.js:51:25)
    at run (worker.js:164:19)
    at eventLoopTick (ext:core/01_core.js:181:11)', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/router-bridge-0.2.8+v2.4.8/src/worker.rs:98:38
```
Please consider handling the errors originating downstream without panics and provide more context.

**Comment by abernix** [comment]
I'll close this issue as it hasn't picked up a lot of traction and we're trying to clean up some old issues.  Please open a new issue with a reproduction if you continue to struggle with this.  Thanks!
